name: ScoltEconomys
version: '1.2.0'
main: me.scoltbr.scoltEconomys.Main
api-version: '1.21'
authors: [ ScoltBr ]
softdepend: [Vault]
description: Plugin de economia focado em inovação
commands:
  money:
    description: Comando principal de economia.
    usage: /money
  eco:
    description: Comandos administrativos.
    usage: /eco <...>
  pay:
    description: Atalho para /money pay
    usage: /pay <player> <amount>
  bolsa:
    description: Mercado de Ações Virtual
    usage: /bolsa [subcomando]
permissions:
  scolteconomy.admin:
    default: op
  scolteconomy.stock:
    description: Permite usar o Mercado de Ações
    default: true